{% set version = "4033.92" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fgarch
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fGarch_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fGarch/fGarch_{{ version }}.tar.gz
  sha256: c835682001c05b178206c8394b3f7ec4e2b96a7d24f8e4ebc68dceae4367140d

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - r-base
    - r-matrix >=1.5_0
    - r-cvar >=0.5
    - r-fbasics
    - r-fastica
    - r-timedate
    - r-timeseries
  run:
    - r-base
    - r-matrix >=1.5_0
    - r-cvar >=0.5
    - r-fbasics
    - r-fastica
    - r-timedate
    - r-timeseries

test:
  commands:
    - $R -e "library('fGarch')"           # [not win]
    - "\"%R%\" -e \"library('fGarch')\""  # [win]

about:
  home: https://www.rmetrics.org
  dev_url: https://r-forge.r-project.org/scm/viewvc.php/pkg/fGarch/?root=rmetrics
  license: GPL-2.0-only
  summary: Provides a collection of functions to analyze and model heteroskedastic behavior in financial time series models.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
